### ISSUE TITLE
edge labels not rendered

### ISSUE THREAD

**Issue by VladimirAlexiev** [zazuko/SPEX#38]
Edges should show property CURIES but I've never seen edge labels?

**Comment by l00mi** [comment]
Not sure to understand this issue, can you elaborate?

**Comment by VladimirAlexiev** [comment]
Edges should have a label, being the shortened prop name

**Comment by l00mi** [comment]
That is not our preferred way to visualize edges with this specific tool.

A bit of context, this tool was specifically build to help developers which do not work on a daily base with linked data to understand RDF models. That is why we developed naturally and deliberately a more UMLish presentation here, which is familiar to RDB people. Because of this reason we like to keep it here, anyhow no fun in developing the same tool again and again, we like to keep it a bit different from what is out there.

In addition:
* Adding Labels on edges makes the overall presentation more chaotic and allows for less information presented.
* We might have with the hover effect showing the edges also let appear the edge label.
